name: CD with Windows
on:
    workflow_dispatch:

jobs:
    test-windows-cmd:
        runs-on: self-hosted
        steps:
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.

            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'microsoft'
                cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml

