name: CD with Windows
on:
    workflow_dispatch:

jobs:
    test-windows-cmd:
        runs-on: self-hosted
        steps:
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.

            - name: Download artifact from github
              uses: actions/download-artifact@v2
              with:
                name: windows-artifact
                path: C:\temp\artifact
                

